stages:
- build

osx:
    stage: build
    script: 
        - atpm fetch
        - atbuild check
        - atbuild package
    tags:
        - openswift
        - atpm
        - atbuild
        - iosDevice
    artifacts:
        paths:
            - bin/package-framework-*.tar.xz
            - bin/package-framework.rb
